name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout theos/theos
        uses: actions/checkout@main
        with:
          repository: theos/theos
          ref: master
          submodules: recursive
          path: theos

      - name: Checkout theos/sdks
        uses: actions/checkout@main
        with:
          repository: theos/sdks
          ref: master
          sparse-checkout: iPhoneOS16.5.sdk
          path: theos/sdks

      - name: Ensure main utils are installed
        uses: dhinakg/procursus-action@main
        with:
          packages: coreutils make xz ldid
          
      - name: Build
        id: build
        run: |
          export THEOS=$HOME/theos

          git submodule init
          git submodule update
          gmake package FINALPACKAGE=1

          # Find the relative path of the .ipa file and store it in an environment variable
          IPA_PATH=$(find . -name "*.ipa" -type f)
          echo "::set-output name=ipa_path::$IPA_PATH"

      - name: List contents of packages directory
        run: ls -la packages

      - name: Move IPA to root directory
        run: mv ${{ steps.build.outputs.ipa_path }} ${{ github.workspace }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: com.yellowcat98.sillyiosapp.ipa 
          path: ${{ github.workspace }}/*.ipa  # Upload the .ipa file from the root directory
