name: Build and Package IPA

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Ensure main utils are installed
        uses: dhinakg/procursus-action@main
        with:
          packages: coreutils make xz ldid

      - name: Install Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git ~/theos
          export THEOS=~/theos

      - name: Compile and Package Tweak
        run: |
          make package FINALPACKAGE=1
          # Move the generated IPA file to the root directory
          mv *.ipa $GITHUB_WORKSPACE/com.yellowcat98.sillyiosapp.ipa || true
        env:
          CPATH: :/opt/procursus/include
          LIBRARY_PATH: :/opt/procursus/lib

      - name: Upload IPA
        uses: actions/upload-artifact@v3
        with:
          name: com.yellowcat98.sillyiosapp.ipa
          path: com.yellowcat98.sillyiosapp.ipa
