name: iOS Build (Unsigned IPA)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install CMake
      run: brew install cmake

    - name: Install Xcode command line tools
      run: sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer

    - name: Configure CMake for iOS
      run: |
        cmake -G Xcode \
              -DCMAKE_SYSTEM_NAME=iOS \
              -DCMAKE_OSX_ARCHITECTURES=arm64 \
              -DCMAKE_OSX_SYSROOT=iphoneos \
              -DCMAKE_OSX_DEPLOYMENT_TARGET=12.0 \
              -B build

    - name: Build iOS Project (Archive without Signing)
      run: |
        xcodebuild archive \
          -project build/sillyiOSApp.xcodeproj \
          -scheme sillyiOSApp \
          -archivePath build/sillyiOSApp.xcarchive \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO
      
    - name: cehck if that thing exosts
      run: ls -R build/..
    
    - name: Convert info.plist to XML
      run: plutil -convert xml1 build/Release-iphoneos/sillyiOSApp.app/info.plist

    - name: Include Storyboard in .appbundle
      run: cp ${{ github.workspace }}/LaunchScreen.storyboard build/Release-iphoneos/sillyiOSApp.app/

    - name: Create Unsigned IPA
      run: |
        mkdir -p Payload
        cp -r build/Release-iphoneos/sillyiOSApp.app Payload/
        zip -r sillyiOSApp.ipa Payload/

    - name: Upload unsigned IPA
      uses: actions/upload-artifact@v3
      with:
        name: sillyiOSApp-unsigned
        path: sillyiOSApp.ipa
    
    - name: Upload Nightly Release
      uses: andelf/nightly-release@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: nightly
        name: 'Nightly'
        prerelease: true
        body: |
          This is the latest build for commit ${{ github.sha }}
          This build isn't meant to be stable. may contain bugs.
        files: sillyiOSApp.ipa
