name: Build and Package IPA

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Ensure main utils are installed
        uses: dhinakg/procursus-action@main
        with:
          packages: coreutils make xz ldid dpkg

      - name: Install Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git ~/theos
          export THEOS=~/theos

      - name: Compile and Package Tweak
        run: |
          make package FINALPACKAGE=1
          # Determine the relative path of the .deb file
          DEB_FILE=$(basename $(ls ./packages/*.deb))
          echo "DEB_FILE=$DEB_FILE" >> $GITHUB_ENV
          # Move the generated .deb file to the root directory
          mv ./packages/$DEB_FILE $GITHUB_WORKSPACE/
        env:
          CPATH: :/opt/procursus/include
          LIBRARY_PATH: :/opt/procursus/lib

      - name: Upload IPA
        uses: actions/upload-artifact@v3
        with:
          name: com.yellowcat98.sillyiosapp.ipa
          path: ${{ env.DEB_FILE }}
