name: Build and Package IPA

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Ensure main utils are installed
        uses: dhinakg/procursus-action@main
        with:
          packages: coreutils make xz ldid

      - name: Compile and Package Tweak
        run: |
          export THEOS=theos
          make package FINALPACKAGE=1
        env:
          CPATH: :/opt/procursus/include
          LIBRARY_PATH: :/opt/procursus/lib

      - name: Upload IPA
        uses: actions/upload-artifact@v2
        with:
          name: com.yellowcat98.sillyiosapp.ipa
          path: packages/*.ipa
