name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout theos/theos
        uses: actions/checkout@main
        with:
          repository: theos/theos
          ref: master
          submodules: recursive
          path: theos

      - name: Checkout theos/sdks
        uses: actions/checkout@main
        with:
          repository: theos/sdks
          ref: master
          sparse-checkout: iPhoneOS16.5.sdk
          path: theos/sdks

      - name: Ensure main utils are installed
        uses: dhinakg/procursus-action@main
        with:
          packages: coreutils make xz ldid
          
      - name: Build
        run: |
          export THEOS=$HOME/theos

          git submodule init
          git submodule update
          gmake package FINALPACKAGE=1

      - name: Move IPA to packages directory
        run: |
          shopt -s nullglob
          ipa_files=(./*.ipa)
          if [ ${#ipa_files[@]} -eq 0 ]; then
            echo "No .ipa file found."
            exit 1
          else
            mv "$ipa_file" packages/
            echo "Moved $ipa_file to packages directory."
          fi

      - name: List contents of packages directory
        run: ls -la packages/

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: com.yellowcat98.sillyiosapp.ipa
          path: packages/*.ipa
