name: Build .dylib for iOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        brew install cmake
        brew install ninja

    - name: Configure CMake
      run: |
        mkdir -p build
        cd build
        cmake -G Ninja \
              -DCMAKE_OSX_SYSROOT=iphoneos \
              -DCMAKE_OSX_ARCHITECTURES=arm64 \
              -DCMAKE_BUILD_TYPE=Release \
              -DCMAKE_INSTALL_PREFIX=../install \
              ..

    - name: Build .dylib
      run: |
        cd build
        cmake --build . --target install

    - name: Copy .dylib to output directory
      run: |
        mkdir -p output
        cp -R install/lib/*.dylib output/

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dylib
        path: output/*.dylib
