name: iOS Build (Unsigned IPA)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install CMake
      run: brew install cmake

    - name: Install Xcode command line tools
      run: sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer

    - name: Configure CMake for iOS
      run: |
        cmake -G Xcode \
              -DCMAKE_SYSTEM_NAME=iOS \
              -DCMAKE_OSX_ARCHITECTURES=arm64 \
              -DCMAKE_OSX_SYSROOT=iphoneos \
              -DCMAKE_OSX_DEPLOYMENT_TARGET=12.0 \
              -B build

    - name: Build iOS Project (Archive without Signing)
      run: |
        xcodebuild archive \
          -project build/MyiOSProject.xcodeproj \
          -scheme MyiOSLib \
          -archivePath build/MyiOSLib.xcarchive \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO
      
    - name: cehck if that thing exosts
      run: ls -R build/../output
    
    - name: Convert info.plist to XML
      run: plutil -convert xml1 build/Release-iphoneos/MyiOSLib.app/info.plist

    - name: Create Unsigned IPA
      run: |
        mkdir -p Payload
        cp -r build/Release-iphoneos/MyiOSLib.app Payload/
        zip -r MyiOSLib.ipa Payload/

    - name: Upload unsigned IPA
      uses: actions/upload-artifact@v3
      with:
        name: MyiOSLib-unsigned
        path: MyiOSLib.ipa
