name: Build and Package iOS App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install CMake
        run: |
          brew install cmake

      - name: Check Xcode Version
        run: /usr/bin/xcodebuild -version

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config Release --target ALL_BUILD

      - name: Package IPA
        run: |
          xcodebuild -workspace YourWorkspace.xcworkspace -scheme YourScheme -configuration Release clean archive -archivePath ${{github.workspace}}/build/YourApp.xcarchive
          xcodebuild -exportArchive -archivePath ${{github.workspace}}/build/YourApp.xcarchive -exportPath ${{github.workspace}}/build -exportOptionsPlist exportOptions.plist

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v2
        with:
          name: YourApp-iOS
          path: ${{github.workspace}}/build/*.ipa
