name: iOS Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install CMake
      run: brew install cmake

    - name: Install Xcode command line tools
      run: sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer

    - name: Configure CMake for iOS
      run: |
        cmake -G Xcode \
              -DCMAKE_SYSTEM_NAME=iOS \
              -DCMAKE_OSX_ARCHITECTURES=arm64 \
              -DCMAKE_OSX_SYSROOT=iphoneos \
              -DCMAKE_OSX_DEPLOYMENT_TARGET=12.0 \
              -B build

    - name: Build iOS Project
      run: cmake --build build --config Release --target MyiOSLib

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: MyiOSLib
        path: build/Release-iphoneos/
