name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout theos/theos
        uses: actions/checkout@main
        with:
          repository: theos/theos
          ref: master
          submodules: recursive
          path: theos

      - name: Checkout theos/sdks
        uses: actions/checkout@main
        with:
          repository: theos/sdks
          ref: master
          sparse-checkout: iPhoneOS16.5.sdk
          path: theos/sdks

      - name: Ensure main utils are installed
        uses: dhinakg/procursus-action@main
        with:
          packages: coreutils make xz ldid
          
      - name: Build
        run: |
          export THEOS=$HOME/theos

          git submodule init
          git submodule update
          make package

          # Debugging: List contents of root directory
          ls -la

          # Set the IPA_FILE environment variable to the desired output name
          echo "IPA_FILE=com.yellowcat98.sillyiosapp.ipa" >> $GITHUB_ENV

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: com.yellowcat98.sillyiosapp.ipa
          path: ${{ github.workspace }}/${{ env.IPA_FILE }}
